# Online Retail Data Cleaning

This notebook performs initial cleaning and preprocessing of the Online Retail dataset.

Key tasks:
- Inspect dataset structure
- Handle missing values
- Remove cancelled transactions
- Remove negative quantities
- Create revenue feature
- Save cleaned dataset for analysis

## Import Libraries and Load Dataset

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"D:\Datasets\Research\retail_analytics_sql_python\data\raw\Online_Retail.csv", encoding="ISO-8859-1")

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/2010 08:26,3.39,17850.0,United Kingdom

In [ ]:
# Dataset size
df.shape

(541909, 8)

In [9]:
# Dataset Structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [10]:
# Summary Statistics
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [11]:
# Missing Values
df.isna().sum().sort_values(ascending=False)

CustomerID     135080
Description      1454
InvoiceNo           0
StockCode           0
Quantity            0
InvoiceDate         0
UnitPrice           0
Country             0
dtype: int64

In [12]:
# Remove Missing Customer IDs (Customer ID is required for customer-level analysis and segmentation)
df = df.dropna(subset=["CustomerID"])

In [13]:
# Remove Cancelled Transactions (Invoices starting with "C" represent cancelled orders).
df = df[~df["InvoiceNo"].astype(str).str.startswith("C")]

In [14]:
# Remove Negative Quantities
df = df[df["Quantity"] > 0]

In [15]:
# Remove Invalid Prices
df = df[df["UnitPrice"] > 0]

In [16]:
# Create Revenue Feature Using Quantity and Unit Price
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

In [ ]:
# Convert Invoice Date to Date Format (The dataset uses day-first datetime format (`dd/mm/yyyy hh:mm`), so `dayfirst=True` is required.)
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], dayfirst=True)

In [21]:
# Save the Cleaned Dataset
df.to_csv("../data/processed/retail_cleaned.csv", index=False)